# Generated by Django 4.2.7 on 2023-12-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_fav_climbing_discipline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fav_wall_angle',
            new_name='fav_wall_type',
        ),
    ]
