# Generated by Django 4.2.7 on 2023-12-08 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardHolds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField(blank=True, null=True)),
                ('y_coordinate', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('function', models.CharField(blank=True, max_length=50)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, max_length=50)),
                ('size', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('angle', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteHolds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_route', models.CharField(blank=True, max_length=50)),
                ('foot_restriction', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.boardholds')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.route')),
            ],
        ),
    ]
